model:
 _target_: attention_jax.config.configuration_transformer.TransformerConfig
 vocab_size: 27
 n_embed: 32
 n_attention_heads: 1
 n_transformer_block: 1
 pad_token_id: 0
 dropout_rate: 0.0
 seq_len: 15